SELECT 
          CAST(A.PIN AS VARCHAR2(50)) AS PROVIDED_PIN_NO,
          A.FIRST_NAME,
          A.MIDDLE_NAME, 
          A.LAST_NAME,
          A.OTHER_NAMES AS OTHER_NAME,
          A.NIN AS JAMII_NO,
          A.DATE_OF_BIRTH AS BIRTH_DATE,
          B.ID AS BIRTH_REG_ID,
          B.NOTIFICATION_NUMBER,
          B.OLD_REGISTRATION_NUMBER AS OLD_PIN_NO,
          B.REGISTRATION_DATE,
          B.CREATED_DATE,
          B.MODIFIED_BY AS LAST_UPDATED_BY_ID,
          B.MODIFIED_DATE AS LAST_UPDATED_DATE,
          A.REGION_OF_BIRTH_ID AS REGION_BIRTH_ID,
          A.DISTRICT_OF_BIRTH_ID AS DISTRICT_BIRTH_ID, 
          A.WARD_OF_BIRTH_ID AS WARD_BIRTH_ID,
          A.COUNTRY_OF_BIRTH_ID AS COUNTRY_BIRTH_ID,
          H.CODE AS SEX_CODE,
          H.DESCRIPTION AS SEX_DESCRIPTION,
          B.PLACE_OF_BIRTH_ID,
          B.HOSPITAL_ID AS FACILITY_ID,
          B.HOSPITAL_NAME AS FACILITY_NAME,
          B.MOTHER_ID,
          B.FATHER_ID,
          B.CERTIFICATE_PRINT_DATE AS FIRST_PRINTED_DATE,
          B.CERTIFICATE_PRINT_BY,
          B.TYPE_OF_BIRTH_ID,
          B.WEIGHT_AT_BIRTH,
          B.STATUS_OF_BIRTH
      FROM CRVS.BIRTH_REGISTRATION B
          INNER JOIN CRVS.PERSON A ON A.ID = B.CHILD_ID
          LEFT JOIN CRVS.SEX H ON A.SEX_ID = H.ID
      WHERE B.CREATED_DATE >= TO_DATE('01-JANUARY-2024', 'DD-MON-YYYY')
      ORDER BY B.ID
