SELECT 
    c.ID, 
    c.DISTRICT_ID, 
    c.CODE, 
    c.NAME, 
    c.POST_CODE, 
    c.ACTIVE,
    c.MVC_UUID,
    d.CODE as DISTRICT_CODE
FROM CRVS.COUNCIL c
LEFT JOIN CRVS.DISTRICT d ON c.DISTRICT_ID = d.ID
