SELECT 
    hf.ID,
    hf.CODE,
    hf.NAME,
    hf.COUNCIL_ID,
    hf.POST_CODE,
    hf.ACTIVE,
    c.CODE AS COUNCIL_CODE,
    c.NAME AS COUNCIL_NAME
FROM crvs.HEALTH_FACILITY hf
LEFT JOIN crvs.COUNCIL c ON hf.COUNCIL_ID = c.ID
ORDER BY hf.CODE
