SELECT 
    hf.ID, 
    hf.CODE, 
    hf.NAME, 
    hf.COUNCIL_ID, 
    hf.POST_CODE, 
    hf.ACTIVE,
    c.CODE as COUNCIL_CODE
FROM CRVS.HEALTH_FACILITY hf
LEFT JOIN CRVS.COUNCIL c ON hf.COUNCIL_ID = c.ID
