SELECT ID, DESCRIPTION, CODE FROM CRVS.REGISTRATION_CENTER_TYPE;
 
SELECT ID, CODE, DESCRIPTION, DESC_SWAHILI FROM CRVS.RELATIONS;
 
SELECT ID, CODE, DESCRIPTION, DESC_SWAHILI FROM CRVS.SEX;
 
SELECT ID, CODE, DESCRIPTION, DESC_SWAHILI, JN_CODE FROM CRVS.TYPE_OF_BIRTH;
 
SELECT ID, CODE, DESCRIPTION FROM CRVS.TYPE_OF_DEATH;
 
SELECT ID, NAME, DESCRIPTION, DESC_SWAHILI, CODE FROM CRVS.TYPE_OF_DISABILITY;
