SELECT 
    rc.ID,
    rc.CODE,
    rc.NAME,
    -- Location Hierarchy
    rc.REGION_ID,
    r.CODE AS REGION_CODE,
    r.NAME AS REGION_NAME,
    
    rc.DISTRICT_ID,
    d.CODE AS DISTRICT_CODE,
    d.NAME AS DISTRICT_NAME,
    
    rc.COUNCIL_ID,
    c.CODE AS COUNCIL_CODE,
    c.NAME AS COUNCIL_NAME,
    
    rc.WARD_ID,
    w.CODE AS WARD_CODE,
    w.NAME AS WARD_NAME,
    
    -- Health Facility Connection
    rc.HEALTH_FACILITY_ID,
    hf.CODE AS HEALTH_FACILITY_CODE,
    hf.NAME AS HEALTH_FACILITY_NAME,
    
    -- Registration Center Properties
    rc.REGISTRATION_FACILITY,
    rc.PRINTING_FACILITY,
    rc.ACTIVE,
    rc.HEAD_OFFICE,
    rc.REGISTRATION_CENTER_TYPE_ID,
    rct.CODE AS REG_CENTER_TYPE_CODE,
    rct.DESCRIPTION AS REG_CENTER_TYPE_DESC,
    rc.REG_TYPE
    
FROM crvs.REGISTRATION_CENTER rc
LEFT JOIN crvs.REGION r ON rc.REGION_ID = r.ID 
LEFT JOIN crvs.DISTRICT d ON rc.DISTRICT_ID = d.ID 
LEFT JOIN crvs.COUNCIL c ON rc.COUNCIL_ID = c.ID 
LEFT JOIN crvs.WARD w ON rc.WARD_ID = w.ID 
LEFT JOIN crvs.HEALTH_FACILITY hf ON rc.HEALTH_FACILITY_ID = hf.ID
LEFT JOIN crvs.REGISTRATION_CENTER_TYPE rct ON rc.REGISTRATION_CENTER_TYPE_ID = rct.ID
WHERE rc.ACTIVE = 1
ORDER BY r.CODE, d.CODE, c.CODE, w.CODE, rc.CODE
