SELECT 
    rc.ID,
    rc.CODE,
    rc.NAME,
    rc.REGION_ID,
    r.CODE AS REGION_CODE,
    r.NAME AS REGION_NAME,
    rc.DISTRICT_ID,
    d.CODE AS DISTRICT_CODE,
    d.NAME AS DISTRICT_NAME,
    rc.COUNCIL_ID,
    c.CODE AS COUNCIL_CODE,
    c.NAME AS COUNCIL_NAME,
    rc.WARD_ID,
    w.CODE AS WARD_CODE,
    w.NAME AS WARD_NAME,
    rc.HEALTH_FACILITY_ID,
    hf.CODE AS HEALTH_FACILITY_CODE,
    hf.NAME AS HEALTH_FACILITY_NAME,
    rc.REGISTRATION_FACILITY,
    rc.PRINTING_FACILITY,
    rc.ACTIVE,
    rc.HEAD_OFFICE,
    rc.REGISTRATION_CENTER_TYPE_ID,
    rct.CODE AS REG_CENTER_TYPE_CODE,
    rct.DESCRIPTION AS REG_CENTER_TYPE_DESC,
    rc.REG_TYPE
FROM CRVS.REGISTRATION_CENTER rc
LEFT JOIN CRVS.REGION r ON rc.REGION_ID = r.ID 
LEFT JOIN CRVS.DISTRICT d ON rc.DISTRICT_ID = d.ID 
LEFT JOIN CRVS.COUNCIL c ON rc.COUNCIL_ID = c.ID 
LEFT JOIN CRVS.WARD w ON rc.WARD_ID = w.ID 
LEFT JOIN CRVS.HEALTH_FACILITY hf ON rc.HEALTH_FACILITY_ID = hf.ID
LEFT JOIN CRVS.REGISTRATION_CENTER_TYPE rct ON rc.REGISTRATION_CENTER_TYPE_ID = rct.ID
ORDER BY rc.ID
