SELECT 
    w.ID, 
    w.CODE, 
    w.NAME, 
    w.COUNCIL_ID, 
    w.POST_CODE, 
    w.ACTIVE,
    c.CODE as COUNCIL_CODE,
    d.CODE as DISTRICT_CODE
FROM CRVS.WARD w
LEFT JOIN CRVS.COUNCIL c ON w.COUNCIL_ID = c.ID
LEFT JOIN CRVS.DISTRICT d ON c.DISTRICT_ID = d.ID
